### ISSUE TITLE
npm install ipip时如果是内网部署的npm源，无法正常安装

### ISSUE THREAD

**Issue by php-cpm** [ChiChou/node-ipip#6]
npm install ipip时如果是内网部署的npm源，由于没有外网权限，无法正常安装，能否设计成跟数据库分离，尤其是环境初始化的时候，如果网络抖动导致下载数据库失败，程序就无法正常执行了

**Comment by ChiChou** [comment]
感谢反馈，其实是已经考虑了这种场景，少了个异常处理。2.2.0 已修复。
